### ISSUE TITLE
Problem setting speed over 4294967295 bits

### ISSUE THREAD

**Issue by h3lll1** [aabc/ipt-ratelimit#13]
Hello, i have a strange problem - i cannot set speed over 4294967295 bits. Going to 4294967296 resets the rule to cir 0. What may be the solution?

**Comment by aabc** [comment]
Yes, counters are 32-bit. Solution is to recode that part.

**Comment by h3lll1** [comment]
you mean long long to add to c code?

**Comment by aabc** [comment]
Sort of. (I may fix it when I get time.) Btw, what value you want to set?

**Comment by h3lll1** [comment]
I want to go up tp 10gbit(thats my network card).

**Comment by h3lll1** [comment]
Let it closed:
nft > ruleset (vmap) > ip > rate limit 
table inet serviceir {
        chain serviceir {
                type filter hook prerouting priority filter; policy accept;
                ip daddr vmap { 10.10.113.2 : jump serviceir-90 };
}
 chain serviceir-90 {
                limit rate over 625000 kbytes/second counter packets 0 bytes 0 drop
        }
|


*** vmap is array of ip: jumps and every jump is 2 checks...

**Comment by h3lll1** [comment]
nft > ratelimit code
