### ISSUE TITLE
End of flow и таймаут

### ISSUE THREAD

**Issue by alexk99** [aabc/ipt-ratelimit#14]
А действительно необходимо ждать истечения idle (inactive) timeout'а для потоков где замечен fin или rst флаг? Ничего не нашел на этот повод в RFC.

static inline int inactive_needs_export(const struct ipt_netflow *nf, const long i_timeout,
    const unsigned long j)
{
	if (likely(i_timeout)) {
		if (unlikely((j - nf->nf_ts_last) > i_timeout)) {
			if (nf->tuple.protocol == IPPROTO_TCP &&
			    FLAG_UP(nf->tcp_flags, TCP_FIN_RST))
				return 0x03; /* end of Flow detected */

**Comment by hotid** [comment]
> RFC 3954        Cisco Systems NetFlow Services Export V9    October 2004


3.2.  Flow Expiration

   A Flow is considered to be inactive if no packets belonging to the
   Flow have been observed at the Observation Point for a given timeout.
   If any packet is seen within the timeout, the flow is considered an
   active flow. A Flow can be exported under the following conditions:

      1. If the Exporter can detect the end of a Flow.  For example, if
         the FIN or RST bit is detected in a TCP [RFC793] connection,
         the Flow Record is exported.

**Comment by alexk99** [comment]
упс. не в тот репозиторий. написал. ну понятно, что спрашиваю, про netflow :)
ну так вот согласно пунтку 1 можно экспортировать поток, как только замечены эти флаги.
вопрос в другом, код, который я привел выше, проверяет флаги, только когда истек idle таймаут.
зачем еще дополнительно ждать истечения idle таймаута?

**Comment by aabc** [comment]
Да можно.

**Comment by aabc** [comment]
Хотя я вот ещё подумал. Раньше при обнаружении `RST|FIN` был таймаут 1 сек, сейчас этот таймаут = `inactive_timeout`. То есть проверку на RST/FIN (для экспорта) можно убрать (что и сделано).

**Comment by alexk99** [comment]
не очень понимаю. т.е. фактически логику обнаружения TCP_FIN_RST решено убрать? почему?
я тоже думаю об 1 секундном таймауте, т.к. замечаю что последний пакет не попадает в поток,
если экспортировать его сразу после rst/fin.

**Comment by alexk99** [comment]
я думал о том, что даже после истечения 1 секунды после обнаружения rst/fin могут прилетать пакеты. но это скорей исключительная ситуация и для них будет тут же создан новый поток, т.е. ждать полноценный idle таймаут (15 секунд) расточительно для tcp.

**Comment by alexk99** [comment]
да. согласен, процедура обнаружения rst/fin не обязательна. тогда это вопрос вкуса получается. а о вкусах не спорят.

**Comment by alexk99** [comment]
последнее соображение. Таймаут 1 сек нигде не определен. Определены active и idle таймауты.
1 секунду в случае rst/fin можно рассматривать как изменение idle таймаута для контректного потока, а не добавление нового таймера.

**Comment by aabc** [comment]
Я сейчас проконсультировался с @enots и он тоже высказался за то, чтоб экспорты были по таймаутам и protocol neutal.

**Comment by alexk99** [comment]
Спасибо. Думаю, вопрос исчерпан.
