### ISSUE TITLE
Проект жив?

### ISSUE THREAD

**Issue by antiuser** [aabc/ipt-ratelimit#23]
Доброго дня! Ввиду появления бесплатного интернета (социально значимых ресурсов) для абонентов с отрицательным балансом хочется через ipt-ratelimit ограничить скорость таким ресурсам до минимума, но меня интересует вопрос - как я могу использовать ipt-ratelimit совместно с ipset.
Объясню, есть таблица в ipset неавторизованных абонентов, которым нужно открыть доступ к таким ресурсам, но я так понимаю ipt-ratelimit не умеет работать с ipset?

Можно в таблицу FORWARD добавлять сети с социальными ресурсами (в ACCEPT конечно), а ratelimit применять к и от абонентского адреса

**Comment by nerosketch** [comment]
Я использую его совместно с ipset. И думаю, что ipt-ratelimit не нужно ничего знать о других правилах, в этом же и прелесть, его можно комбинировать с любыми правилами.
Я бы, наверное, в forward сначала добавил фильтр по ipset, а потом всех оставшихся, кто прошёл его, уже ограничить с помощью ipt-ratelimit

**Comment by nerosketch** [comment]
Я использую его совместно с ipset. И думаю, что ipt-ratelimit не нужно ничего знать о других правилах, в этом же и прелесть, его можно комбинировать с любыми правилами.
Я бы, наверное, в forward сначала добавил фильтр по ipset, а потом всех оставшихся, кто прошёл его, уже ограничить с помощью ipt-ratelimit
