### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by k0ste** [aabc/ipt-ratelimit#24]
Please make new github release, the current is 2 years old 🙂

**Comment by alex-eri** [comment]
https://github.com/aabc/ipt-ratelimit/commit/528827962504db70abcee7eff9612aad2b42fac8

 Tagged at this spring.

**Comment by k0ste** [comment]
Just luck of releases page
![A1E37C1F-2CD1-4F68-B10C-9D085CF4D28F](https://user-images.githubusercontent.com/7759548/188283008-1585e1d8-f899-48b7-88bf-a17cb5a1463e.png)

Thanks
